### - testes da API - o REST Client
# 1) cadastre os usuários  2) faça o login  3) cole o token abaixo
@token = COLE_O_TOKEN_AQUI

### - Teste se o servidor está funcionando
GET http://localhost:3000/
Content-Type: application/json

### - Teste para Cadastrar o Usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Adalberto",
    "email": "adalberto@gmail.com",
    "senha": "123",
    "cpf": "12345678909",
    "telefone": "47999990000"
}

### - Teste para Cadastrar o Usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Marcos",
    "email": "marcos@gmail.com",
    "senha": "123",
    "cpf": "12345678909",
    "telefone": "47999990000"
}

### - Teste para Cadastrar o Usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Ronaldo",
    "email": "ronaldo@gmail.com",
    "senha": "123",
    "cpf": "12345678909",
    "telefone": "47999990000"
}


### - Teste de Login (copie o token retornado e cole em @token abaixo)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "adalberto@gmail.com",
    "senha": "123"
}

### - Teste de Login com senha errada (esperado 401)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "adalberto@gmail.com",
    "senha": "errada"
}

### - Teste para Listar o Usuário

GET http://localhost:3000/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Consultar o Usuário
GET http://localhost:3000/usuario/1
Content-Type: application/json
Authorization: Bearer {{token}}


### - Teste para Consultar o Usuário por nome
GET http://localhost:3000/usuario/buscar/marcos
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Excluir o Usuário
DELETE http://localhost:3000/usuario/4
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Atualizar o Usuário
PUT http://localhost:3000/usuario/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Rodrigo",
    "email": "rodrigo@gmail.com",
    "senha": "456",
    "cpf": "98765432100",
    "telefone": "47988880000"
}


################################

### - Teste para Cadastrar o Produto
POST http://localhost:3000/produto
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Nike",
    "categoria": "casual",
    "numero": 38,
    "quantidade": 20,
    "precoUnit": 699.99
}

### - Teste para Cadastrar o Produto
POST http://localhost:3000/produto
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Ultraboost",
    "categoria": "corrida",
    "numero": 40,
    "quantidade": 40,
    "precoUnit": 999.99
}

### - Teste para Cadastrar o Produto
POST http://localhost:3000/produto
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Old Skool Pro",
    "categoria": "skate",
    "numero": 40,
    "quantidade": 20,
    "precoUnit": 399.99
}

### - Teste para Listar o Produto

GET http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Consultar o Produto
GET http://localhost:3000/produto/1
Content-Type: application/json
Authorization: Bearer {{token}}


### - Teste para Consultar o Produto por nome
GET http://localhost:3000/produto/buscar/Nike
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Excluir o Produto
DELETE http://localhost:3000/produto/4
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Atualizar o Produto
PUT http://localhost:3000/produto/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Adidas",
    "categoria": "superStar",
    "numero": 42,
    "quantidade": 10,
    "precoUnit": 550.00
}


#####################################
### - Teste para Cadastrar Movimento

POST http://localhost:3000/movimento
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "idUsuario": 1,
    "idProduto": 1,
    "tipo": "SAIDA",
    "qtdeMov": 10,
    "data": "2026-05-25"
}

### - Teste para Listar o Movimento

GET http://localhost:3000/movimentos
Content-Type: application/json
Authorization: Bearer {{token}}

### - Teste para Listar valor total por categoria (view)

GET http://localhost:3000/relatorio/categorias
Content-Type: application/json
Authorization: Bearer {{token}}


### - Teste para Listar histórico de saídas (view)

GET http://localhost:3000/relatorio/saidas
Content-Type: application/json
Authorization: Bearer {{token}}


